apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Qm9vdGNhbXBANjE=
  MYSQL_DATABASE: emVtb3NvX2RpYWdub3N0aWNz
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovLzMuMjM5Ljg3LjI1NTozMDAwMi96ZW1vc29fZGlhZ25vc3RpY3M/YWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZSZ1c2VTU0w9ZmFsc2Umc2VydmVyVGltZXpvbmU9VVRD