apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-frontend:v3
        ports:
        - containerPort: 80
      
      imagePullSecrets:
      - name: my-ghcr-secret