apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-service-pod
  template:
    metadata:
      labels:
        app: lab-service-pod
    spec:
      containers:
      - name: lab-service-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-lab-service:v3
        ports:
        - containerPort: 9004
      
      imagePullSecrets:
      - name: my-ghcr-secret