apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service-pod
  template:
    metadata:
      labels:
        app: patient-service-pod
    spec:
      containers:
      - name: patient-service-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-patient-service:v3
        ports:
        - containerPort: 9005
      
      imagePullSecrets:
      - name: my-ghcr-secret