apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry-pod
  template:
    metadata:
      labels:
        app: service-registry-pod
    spec:
      containers:
      - name: service-registry-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-service-registry:v3
        ports:
        - containerPort: 8761
      
      imagePullSecrets:
      - name: my-ghcr-secret