apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-pod
  template:
    metadata:
      labels:
        app: user-service-pod
    spec:
      containers:
      - name: user-service-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-user-service:v3
        ports:
        - containerPort: 9008
      
      imagePullSecrets:
      - name: my-ghcr-secret