apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-service-pod
  template:
    metadata:
      labels:
        app: address-service-pod
    spec:
      containers:
      - name: address-service-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-address-service:v3
        ports:
        - containerPort: 9001
      
      imagePullSecrets:
      - name: my-ghcr-secret