apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service-pod
  template:
    metadata:
      labels:
        app: card-service-pod
    spec:
      containers:
      - name: card-service-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-backend-card-service:v3
        ports:
        - containerPort: 9003
      
      imagePullSecrets:
      - name: my-ghcr-secret