apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
      - name: database-pod
        image: ghcr.io/satyanarayana-senapathi/auth0-bootcamp-database:v1
        ports:
        - containerPort: 80
      
      imagePullSecrets:
      - name: my-ghcr-secret