server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: LAB-SERVICE
          uri: lb://LAB-SERVICE
          predicates:
            - Path=/api/labs/**

        - id: CARD-SERVICE
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/api/cards/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/api/address/**

        - id: APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/appointments/**

        - id: TEST-SERVICE
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/tests/**

        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients/** 

        - id: TEST-LAB-SERVICE
          uri: lb://TEST-LAB-SERVICE
          predicates:
            - Path=/api/testlabs/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://bc.spcluster.tk/eureka/
  instance:
    hostname: cloud-gateway-service
