apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort
  selector:
    app: database-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
