name: Deploy backend to GHCR and eks

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    strategy:
        matrix:
            services:
            - address-service
            - user-service
            - appointment-service
            - card-service
            - cloud-gateway
            - lab-service
            - patient-service
            - service-registry
            - test-lab-service
            - test-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_PAT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: adding eks-cluster
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        run: |
            aws eks --region $aws_region update-kubeconfig --name $cluster_name
      - name: Run Strategy
        run: |
            cd ${{ matrix.services }}
            mvn clean package -DskipTests
            docker build -t ghcr.io/${{ github.actor }}/auth0-bootcamp-backend-${{ matrix.services }}:v${{ github.run_number }} .
            docker push ghcr.io/${{ github.actor }}/auth0-bootcamp-backend-${{ matrix.services }}:v${{ github.run_number }}
            kubectl set image deployment/${{ matrix.services }}-deployment ${{ matrix.services }}-pod=ghcr.io/${{ github.actor }}/auth0-bootcamp-backend-${{ matrix.services }}:v${{ github.run_number }}
 





          





    #   - name: Build and Push Docker Image
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: ./backend
    #       push: true
    #       tags: ghcr.io/${{ github.actor }}/auth0-bootcamp-backend:v${{ github.run_number }}
        
    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ secrets.AWS_REGION }}

    #   - name: adding eks-cluster
    #     env: 
    #       aws_region: ${{ secrets.AWS_REGION }}
    #       cluster_name: ${{ secrets.CLUSTER_NAME }}
    #       IMAGE: ghcr.io/${{ github.actor }}/auth0-bootcamp-backend:v${{ github.run_number }}
    #     run: |
    #       aws eks --region $aws_region update-kubeconfig --name $cluster_name
    #       kubectl set image deployment/backend-deployment backend-pod=$IMAGE



#     - name: Check Code Changes
#     id: code_changes
#     run: |
#       echo "::set-output name=changed::false"
#       for file in $(git diff --name-only HEAD HEAD^); do
#         if [[ $file == "${{ matrix.directory }}/"* ]]; then
#           echo "::set-output name=changed::true"
#           break
#         fi
#       done

#   - name: Run Strategy
#     if: steps.code_changes.outputs.changed == 'true'
