name: Deploy backend to GHCR and eks

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    strategy:
        matrix:
            services:
            - address-service
            - user-service
            - appointment-service
            - card-service
            - cloud-gateway
            - lab-service
            - patient-service
            - service-registry
            - test-lab-service
            - test-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_PAT }}


      - name: Run Strategy
        run: |
           cd ${{ matrix.services }}
           mvn clean package -DskipTests
           docker build -t ghcr.io/${{ github.actor }}/auth0-bootcamp-backend-${{ matrix.services }}:v${{ github.run_number }} .
           docker push ghcr.io/${{ github.actor }}/auth0-bootcamp-backend-${{ matrix.services }}:v${{ github.run_number }}
           
 





   