name: build react app image and push to github packages
on:
  push:
    paths:
      - 'frontend/**'
      - '!frontend/db/**'
      - '.github/workflows/frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
        run:
          working-directory: frontend


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --force

      - name: Build application
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.actor }}/auth0-bootcamp-frontend:v${{ github.run_number }}
    
     