name: deploy mock server to ghcr and eks

on:
  push:
    paths:
      - 'frontend/src/mockData/**'
      - '.github/workflows/mock-server.yml'

jobs:
  build:    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/db
          push: true
          tags: ghcr.io/${{ github.actor }}/auth0-bootcamp2-mockserver:v${{ github.run_number }}
          dockerfile: Dockerfile  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1



            

      