name: deploy mock server to ghcr and eks

on:
  push:
    paths:
      - 'frontend/db/**'
      - '.github/workflows/mockserver.yml'

jobs:
  build:    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/db
          push: true
          tags: ghcr.io/${{ github.actor }}/auth0-bootcamp2-mockserver:v${{ github.run_number }}
          dockerfile: Dockerfile  

    


    

      